# Generated by Django 2.2.6 on 2019-10-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empID', models.IntegerField(null=True)),
                ('empName', models.CharField(max_length=20, null=True)),
                ('empMobile', models.IntegerField(null=True)),
                ('empAddress', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
