# Generated by Django 2.2.5 on 2019-10-07 06:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='empdata',
            name='empID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
