# Generated by Django 2.2.5 on 2019-10-07 07:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirst', '0002_auto_20191007_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='justData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('adminName', models.CharField(max_length=20, null=True)),
                ('adminMobile', models.IntegerField(null=True)),
                ('adminAddress', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
