# Generated by Django 2.2.5 on 2019-10-07 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirst', '0003_justdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='justData',
        ),
        migrations.AddField(
            model_name='empdata',
            name='adminAddress',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empdata',
            name='adminID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='empdata',
            name='adminMobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='empdata',
            name='adminName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
