# Generated by Django 2.2.5 on 2019-10-07 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirst', '0004_auto_20191007_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empdata',
            name='adminAddress',
        ),
        migrations.RemoveField(
            model_name='empdata',
            name='adminID',
        ),
        migrations.RemoveField(
            model_name='empdata',
            name='adminMobile',
        ),
        migrations.RemoveField(
            model_name='empdata',
            name='adminName',
        ),
    ]
