# Generated by Django 2.2.5 on 2019-10-07 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('MyFirst', '0005_auto_20191007_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='empID',
            field=models.IntegerField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
